name: Deploy
on:
  push:
    branches:
      - main
jobs:
  container-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Cache purescript dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            .spago
            ${{ env.spago_global_cache }}
            output
          key: >-
            ${{ hashFiles('package-lock.json') }}-
            ${{ hashFiles('spago.dhall') }}-
            ${{ hashFiles('examples.dhall') }}-
            ${{ hashFiles('packages.dhall') }}
      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7.13.2
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - run: pnpm i && pnpm build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
